# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 主页
    url: '#about'
    weight: 10
 # - name: Posts
 #   url: '#posts'
 #   weight: 20
  - name: 科研项目
    url: '#projects'
    weight: 30
 # - name: Talks
 #   url: '#talks'
 #   weight: 40
  - name: 科研成果
    url: '#JournalPapers'
    weight: 50
  - name: 教育背景
    url: '#experience'
    weight: 51
  - name: 学术服务
    url: '#services'
    weight: 52
  - name: 荣誉获奖
    url: '#awards'
    weight: 53
  - name: 联系方式
    url: '#contact'
    weight: 60
  - name: 个人简历
    url: uploads/resume.pdf
    weight: 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
